language: php

php:
  - 5.4
  - 5.5
  - hhvm

before_script:
  - composer install --dev --prefer-source

script: phpunit

notifications:
  email:
    - vincent.composieux@gmail.com
    - andrieu.travail@gmail.com

matrix:
  allow_failures:
    - php: hhvm
